name: Deploy static content to Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          branch: gh-pages
          folder: . # or your build folder if different
